linters:
  enable-all: false
  disable-all: true
  fast: false
  enable:
    - errorlint
    - goerr113
    - nilerr
    - bodyclose
    - goconst
    - prealloc
    - rowserrcheck
    - misspell
    - unconvert
    - errcheck
    - deadcode
    - unused
    